name: Deploy Docker App

on:
  push:
    branches:
      - main  # Trigger on push to main branch (or change to your branch)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # You will add this SSH key later in GitHub Secrets

    - name: Build and push Docker image
      run: |
        docker-compose build  # If you're using docker-compose
        docker-compose up -d

    - name: SSH into server and deploy
      run: |
        ssh -o StrictHostKeyChecking=no user@YOUR_VM_IP << EOF
          cd /path/to/your/project  # Change to the directory where your Docker setup is
          git pull origin main
          docker-compose down
          docker-compose up -d
        EOF
